### ISSUE TITLE
Ошибки JotX

### ISSUE THREAD

**Issue by yuri25** [Temus/JotX#10]
Добрый день. Помогите пожалуйста решить проблему с JotX.
https://github.com/evolution-cms/evolution/issues/1316
И вот здесь посмотрите пожалуйста
http://modx.im/blog/6040.html

**Comment by yuri25** [comment]
Ошибки при отправлении комментариев исчезли... Спасибо. К сожалению вместо комментариев выводит только вот это:  Comments_tplComments
Посмотрите пожалуйста еще в чем может быть проблема.

**Comment by Temus** [comment]
Comments_tplComments - это часть демосайта
