### ISSUE TITLE
JotX - no permission management

### ISSUE THREAD

**Issue by tad54** [Temus/JotX#12]
Hi,
I am using EVO v1.4.17, trying to adapt in my application your last version JotX. I chose him because he promised to work with JoCo module. Unfortunately, when I started to test final instalation I found an issue - permission management doesn't work. It's impossible to set properly params: **&canview**, **&canedit** and **&canmoderate** in the snippet call.
No way to set up those params to make published comments visible for all visitors  - all comments are visible only for logged admin. 
The responsible for it part of code (?) I found in file **jot.class.inc.php** at line 136 and below. Can you verify is it true? It looks like an unfinished part of code (comment in line 149 - "no logic for manager groups"). Unfortunately all previous versions of this file have are identical in this part of code. It was left here intentionally? 

It would be a pity to problem like that makes this snippet not useful.
Or maybe I am wrong and making any mistake? Can you help me?
Regards
Tad

PS. My JotX call:
	[!JotX? 
	&tplForm=`Comments_tplForm`
	&customfields=`name,email` 
	&subscribe=`1` 
	&pagination=`4` 
	&badwords=`dotNet`	
	&canedit=`web_users`
	&canmoderate=`TePe`	 
	&canpost=`web_users`
	&canview=``
	&debug=`1`
	!] 
Unfortunately, I am not a programmer...

**Comment by Temus** [comment]
Remove **&canview=``**

**Comment by tad54** [comment]
It really works! - not intuitive, but radical and effective move. 
You're great - a lot of thanks. 
Regards
Tad
