### ISSUE TITLE
Ошибка «Evo Parse Error» при переходе с PHP 5.6 на 7.3

### ISSUE THREAD

**Issue by tri-motor** [Temus/JotX#14]
При переключении версии PHP с 5.6 на 7.3:

Trying to get property 'action' of non-object
« Evo Parse Error »
Error : count(): Parameter must be an array or an object that implements Countable

**ErrorType[num]** WARNING[2]
**File** assets/snippets/jot/actions/treecomments.inc.php
**Line** 58
**Source** $commentTotal = count($tree[0]);
**Current Snippet** JotX

**Comment by Temus** [comment]
Это давно [исправлено](https://github.com/Temus/JotX/commit/1d9d271f6d09a63005fd11ebaf7cf84683ab42e5)

**Comment by tri-motor** [comment]
JotX устанавливал через Extras в EVO 1.4.15.

**Comment by Temus** [comment]
Отправил запрос на обновление extras
