### ISSUE TITLE
tree-ajax нельзя отменить удаление

### ISSUE THREAD

**Issue by xen-chut** [Temus/JotX#6]
Спасибо за великолепный сниппет!
При &config=`tree-ajax` когда удаляешь комментарии появляется сообщение "Вы действительно хотите удалить это сообщение?" и две кнопки "ОК" и "Отмена", если нажать кнопку "Отмена" сообщение все равно удаляется. Догадываюсь что проблема в том что при использовании ajax подключается файл /assets/snippets/jot/js/ajax.js и в нем вешается делегат который игнорирует этот confirm на ссылке "удалить", поправить никак не получается =(

**Comment by Temus** [comment]
Этот баг ещё год назад исправлен. Обновите файлы, если скачали с evolution-cms или ещё откуда-нибудь.
