### ISSUE TITLE
Ошибка PHP 7 Error : preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead 

### ISSUE THREAD

**Issue by Kettah** [Temus/JotX#7]
ErrorType[num]  WARNING[2]
File    /home/public_html/assets/snippets/jot/includes/phx.parser.class.inc.php
Line    254
Source  $output = preg_replace("~(\b\w+\b)~e","wordwrap('\\1',\$wrapat,' ',1)",$output);
Current Snippet     Jot
Error : preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead 

Решение 
$output = preg_replace_callback("~(\b\w+\b)~", 
  function($matches) use($wrapat) { 
    return wordwrap($matches[0], $wrapat, ' ', 1); 
  }, $output); 

Отсюда 
https://github.com/modxcms/evolution/issues/716 
Обновите в репозитории

**Comment by Temus** [comment]
Сделал немного попроще для совместимости.
